name: build-nopch
on:
  push:
    tags-ignore: v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ninja and g++13
        run: sudo apt update -yqq && sudo apt install -yqq ninja-build xorg-dev g++-13
      - name: update to clang 16
        run: sudo wget https://apt.llvm.org/llvm.sh && sudo chmod +x llvm.sh && sudo ./llvm.sh 16
      - name: configure gcc
        run: cmake -S . --preset=default -B build -DCMAKE_CXX_COMPILER=g++-13 -DGENESIS_PCH=OFF
      - name: configure clang
        run: cmake -S . --preset=default -B clang -DCMAKE_CXX_COMPILER=clang++-16 -DGENESIS_PCH=OFF
      - name: build gcc debug
        run: cmake --build build --config=Debug
      - name: build clang debug
        run: cmake --build clang --config=Debug

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake -S . --preset=vs22 -B build -DGENESIS_PCH=OFF
      - name: build debug
        run: cmake --build build --config=Debug
