name: build
on:
  push:
    tags-ignore: v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: install homebrew formulae
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install ninja
        run: brew install ninja gcc@11
      - name: update AppleClang to 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
      - name: configure clang
        run: cmake -S . --preset=ninja-clang -B clang
      - name: build clang
        run: cmake --build clang --config=Release
      - name: test
        run: cd build && ctest -C Release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ninja and g++13
        run: sudo apt update -yqq && sudo apt install -yqq ninja-build xorg-dev g++-13
      - name: update to clang 16
        run: sudo apt --purge remove python3-lldb-14 && sudo wget https://apt.llvm.org/llvm.sh && sudo chmod +x llvm.sh && sudo ./llvm.sh 16
      - name: configure gcc
        run: cmake -S . --preset=default -B build -DCMAKE_CXX_COMPILER=g++-13
      - name: configure clang
        run: cmake -S . --preset=default -B clang -DCMAKE_CXX_COMPILER=clang++-16
      - name: configure gcc no pch
        run: cmake -S . --preset=ninja-nopch -B nopch -DCMAKE_CXX_COMPILER=clang++-16
      - name: build gcc release
        run: cmake --build build --config=Release
      - name: build gcc debug
        run: cmake --build build --config=Debug
      - name: build clang release
        run: cmake --build clang --config=Release
      - name: build clang debug
        run: cmake --build clang --config=Debug
      - name: build no pch
        run: cmake --build nopch --config=Debug

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake -S . --preset=vs22 -B build
      - name: configure nopch
        run: cmake -S . --preset=vs22-nopch -B nopch
      - name: build release
        run: cmake --build build --config=Release
      - name: build debug
        run: cmake --build build --config=Debug
      - name: build no pch
        run: cmake --build nopch --config=Debug
